"""Week 3 configuration. Shipped complete. Associates do not edit this file.

Every constant the week's assignments name is here rather than at a call site,
so that a value can be found, changed, and reviewed in one place.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Repository layout
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]

CORPUS_SOURCE_DIR = REPO_ROOT / "corpus" / "source"
CORPUS_MANIFEST = REPO_ROOT / "corpus" / "manifest.json"
CASE_QUESTION_DIR = REPO_ROOT / "cases" / "questions"
CASE_GOLD_DIR = REPO_ROOT / "cases" / "gold"
EXAMPLE_QUESTION_DIR = REPO_ROOT / "examples" / "questions"
PROMPT_DIR = Path(__file__).resolve().parent / "prompts"
RUN_DIR = REPO_ROOT / "runs"
REPORT_DIR = REPO_ROOT / "reports"

# ---------------------------------------------------------------------------
# Models
#
# The embedding deployment name is per Associate, because Associates create
# their own Azure deployments. The model identifier and the vector dimension
# are pinned here, and the store's vector column is created against the
# dimension so that a mismatch fails at insert rather than degrading silently.
# ---------------------------------------------------------------------------

EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMENSION = 1536
EMBEDDING_DEPLOYMENT_ENV = "AZURE_OPENAI_EMBEDDING_DEPLOYMENT"

# One generation model for the week, used for query rewriting, answering, and
# reranking. Both Week 2 adapters remain available.
#
# TO SWITCH PROVIDER: change these two lines together. Nothing else needs to
# change, because rag.models.generation_adapter() is the only place an adapter
# is constructed. Valid pairs:
#
#     ("anthropic",    "claude-sonnet-5")   requires ANTHROPIC_API_KEY
#     ("azure_openai", "gpt-5-mini")        requires the Azure chat deployment
#
# Azure is the only provider Day 1 needs, because Day 1 is embeddings only.
GENERATION_PROVIDER = "anthropic"
GENERATION_MODEL = "claude-sonnet-5"
GENERATION_TEMPERATURE = 0.0

# ---------------------------------------------------------------------------
# Cost
#
# US dollars per million tokens. Verify against current provider pricing before
# quoting any cost figure in a report. Embedding models are priced on input
# tokens only.
# ---------------------------------------------------------------------------

PRICING_USD_PER_MTOK: dict[str, dict[str, float]] = {
    "claude-sonnet-5": {"input": 2.00, "output": 10.00},
    "gpt-5-mini": {"input": 0.25, "output": 2.00},
    "text-embedding-3-small": {"input": 0.02, "output": 0.00},
}

SPEND_CEILING_USD = 20.0
RUN_CAP_USD = 2.0

# Both directories are summed when the running total is computed, so that an
# embedding call and a completion call draw on one budget.
SPEND_RECORD_DIRS = (RUN_DIR / "completions", RUN_DIR / "embeddings")

# ---------------------------------------------------------------------------
# Chunking (Day 1)
# ---------------------------------------------------------------------------

CHUNK_MAX_CHARS = 1200
CHUNK_OVERLAP_CHARS = 150
CHUNK_STRATEGY = "section-first-v1"

# ---------------------------------------------------------------------------
# Retrieval (Day 2, widened for reranking on Day 4)
#
# RETRIEVER_K is what each retriever returns. RERANK_INPUT_K is what the union
# retains and hands to the reranker. FUSED_K is what reaches assembly. The
# first stage optimizes recall and the second optimizes precision, so
# RETRIEVER_K and RERANK_INPUT_K are both larger than FUSED_K.
# ---------------------------------------------------------------------------

RETRIEVER_K = 20
RERANK_INPUT_K = 24
FUSED_K = 8
RRF_CONSTANT = 60

MAX_PASSES = 3
MAX_STEPS = 5

# ---------------------------------------------------------------------------
# Assembly (Day 3)
# ---------------------------------------------------------------------------

CONTEXT_TOKEN_BUDGET = 3000

# When exact duplicate text is collapsed before assembly, the copy from the
# family that is the source of the requirement survives, rather than the copy
# from a document that quotes it. Lower index wins.
FAMILY_PRECEDENCE: tuple[str, ...] = (
    "kyc_periodic_review",
    "card_dispute_procedure",
    "compliance_manual",
)

# ---------------------------------------------------------------------------
# Evaluation (Day 4)
#
# A claim's literals must each appear in at least one chunk that claim cites.
# Defined terms are drawn from the corpus definitions sections and are matched
# case-insensitively as whole phrases.
# ---------------------------------------------------------------------------

LITERAL_PATTERNS: dict[str, re.Pattern[str]] = {
    "percentage": re.compile(r"\b\d+(?:\.\d+)?\s*percent\b", re.IGNORECASE),
    "duration": re.compile(
        r"\b(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|\d+)\s+"
        r"(?:day|days|week|weeks|month|months|year|years)\b",
        re.IGNORECASE,
    ),
    "date": re.compile(r"\b\d{4}-\d{2}-\d{2}\b"),
    "section_reference": re.compile(r"\bSection\s+\d+(?:\.\d+)*\b", re.IGNORECASE),
    "number": re.compile(r"(?<![\w.])\d+(?:\.\d+)?(?![\w.])"),
}

DEFINED_TERMS: tuple[str, ...] = (
    "beneficial owner",
    "beneficial ownership",
    "certificate of good standing",
    "compelling evidence",
    "enhanced due diligence",
    "listed jurisdictions",
    "partnership agreement",
    "partnership interest",
    "periodic review",
    "politically exposed person",
    "registered address",
    "representment",
    "risk rating",
    "simplified due diligence",
    "source of funds",
)

# ---------------------------------------------------------------------------
# Store
# ---------------------------------------------------------------------------


def database_url() -> str:
    """Connection details come from the environment and enter no commit."""
    user = os.environ["PGUSER"]
    password = os.environ["PGPASSWORD"]
    host = os.environ["PGHOST"]
    port = os.environ.get("PGPORT", "5432")
    database = os.environ["PGDATABASE"]
    return f"postgresql://{user}:{password}@{host}:{port}/{database}"
